name: Database Backup (manual)

on:
  workflow_dispatch: {}

jobs:
  pg_dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Create dump
        env:
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          PGSSLMODE: ${{ secrets.PGSSLMODE }}
        run: |
          ts=$(date -u +"%Y-%m-%dT%H-%M-%SZ")
          outfile="db_${PGDATABASE}_${ts}.dump"
          pg_dump -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -Fc --no-owner --no-privileges -f "$outfile"
          echo "OUTFILE=$outfile" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: db-backup
          path: ${{ env.OUTFILE }}
          retention-days: 7
